language: php

php:
  - '7.1'

cache:
  directories:
    - $HOME/.npm
    - $HOME/.composer/cache

before_install:
  - nvm install 6.5.0
  - nvm use 6.5.0

install:
  - npm install
  - pecl install -f ast-0.1.6
  - phpenv config-rm xdebug.ini
  - composer install --prefer-dist

script:
  - npm run lint
    # The typescript declaration files have minor errors in node_modules.
    # These should go away in later vscode* dependencies
  - npm run build || true

# If build on a tag, publish a new release and upload vsix to the GitHub release
before_deploy:
  - ./node_modules/.bin/vsce package
  - ./node_modules/.bin/vsce publish -p $VSCE_TOKEN

# TODO: Re-introduce deploy section
branches:
  only:
    - master

notifications:
 email: false
