language: php

php:
  - '7.1'

cache:
  directories:
    - $HOME/.npm
    - $HOME/.composer/cache

before_install:
  - nvm install 6.5.0
  - nvm use 6.5.0

install:
  - npm install
  - pecl install -f ast-0.1.6
  - phpenv config-rm xdebug.ini
  - composer install --prefer-dist

script:
  - npm run lint
  - npm run build

# TODO: Re-introduce deploy section
branches:
  only:
    - master

notifications:
  email: false
