language: php

php:
  - 7.2
  - 7.3
  - 7.4

matrix:
  exclude:
  - php: 7.4
    env: NODE_VERSION=12
  - php: 7.3
    env: NODE_VERSION=10
  - php: 7.1
    env: NODE_VERSION=8
  - php: 7.2
    env: NODE_VERSION=8

env:
  - NODE_VERSION=6.5.0
  - NODE_VERSION=8
  - NODE_VERSION=10

cache:
  directories:
    - $HOME/.npm
    - $HOME/.composer/cache

before_install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

install:
  - npm install
  # Installing ast isn't even necessary because there are no integration tests right now.
  # - pecl install -f ast-1.0.1
  - phpenv config-rm xdebug.ini
  - composer install --prefer-dist
  - vendor/bin/phan --help

script:
  - npm run lint
  - npm run build

# TODO: Re-introduce deploy section
branches:
  only:
    - master

notifications:
  email: false
