language: php

php:
  - 7.0
  - 7.1
  - 7.2

matrix:
  exclude:
  - php: 7.0
    env: NODE_VERSION=6.5.0
  - php: 7.0
    env: NODE_VERSION=10
  - php: 7.1
    env: NODE_VERSION=8
  - php: 7.1
    env: NODE_VERSION=10
  - php: 7.2
    env: NODE_VERSION=8

env:
  - NODE_VERSION=6.5.0
  - NODE_VERSION=8
  - NODE_VERSION=10

cache:
  directories:
    - $HOME/.npm
    - $HOME/.composer/cache

before_install:
  - nvm install $NODE_VERSION
  - nvm use $NODE_VERSION

install:
  - npm install
  - pecl install -f ast-0.1.7
  - phpenv config-rm xdebug.ini
  - composer install --prefer-dist

script:
  - npm run lint
  - npm run build

# TODO: Re-introduce deploy section
branches:
  only:
    - master

notifications:
  email: false
